project_id = "kvaqlehxmaynwvlpowpa"

[functions.spotify-auth]
verify_jwt = false

[functions.spotify-browse]
verify_jwt = false

[functions.spotify-public-config]
verify_jwt = false

[functions.bunny-audit]
verify_jwt = false
